language: julia
os:
    - linux
julia:
    - 1.0
notifications:
    email: false
sudo: false
branches:
  only:
    - master
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); cd(Pkg.dir("DiffOpt")); using Coverage; Coveralls.submit(process_folder())'
