language: julia
os:
    - linux
julia:
    - 1.0
notifications:
    email: false
sudo: false
branches:
  only:
    - master
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
