language: julia
os:
    - linux
julia:
    - 1.0  # JuMP currently supports Julia 1.0 LTS
    - 1.4
notifications:
    email: false
sudo: false
branches:
  only:
    - master
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); cd(Pkg.dir("DiffOpt")); using Coverage; Coveralls.submit(process_folder())'
  - julia --project examples/solve-LP.jl
  - julia --project examples/solve-QP.jl


name: Documentation

on:
  push:
    branches:
      - master
      - create_docs
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.4'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
