language: julia
os:
    - linux
julia:
    - 1.0  # JuMP currently supports Julia 1.0 LTS
    - 1.4
notifications:
    email: false
sudo: false
branches:
  only:
    - master
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); cd(Pkg.dir("DiffOpt")); using Coverage; Coveralls.submit(process_folder())'
  - julia --project examples/solve-LP.jl
  - julia --project examples/solve-QP.jl
